import { type LocExamState, type NeuroExamData } from './types';

// ─── Localization Display Names ──────────────────────────────────────────────

export const LOC_NAMES: Record<string, string> = {
  prosencephalon: 'Prosencephalon (Forebrain)',
  brainstem: 'Brainstem',
  cerebellum: 'Cerebellum',
  periph_vest: 'Peripheral Vestibular',
  c1c5: 'C1–C5 Myelopathy',
  c6t2: 'C6–T2 Myelopathy (Cervical Intumescence)',
  t3l3: 'T3–L3 Myelopathy',
  l4s3: 'L4–S3 Myelopathy (Lumbosacral Intumescence)',
  multifocal: 'Multifocal / Diffuse',
};

// ─── Nav Button Config ───────────────────────────────────────────────────────

export const LOC_NAV = [
  { id: 'prosencephalon' as const, label: 'Prosencephalon', sub: 'Forebrain' },
  { id: 'brainstem' as const, label: 'Brainstem', sub: 'Intracranial' },
  { id: 'cerebellum' as const, label: 'Cerebellum', sub: 'Intracranial' },
  { id: 'periph_vest' as const, label: 'Periph. Vest.', sub: 'Inner Ear / CN VIII' },
  { id: 'c1c5' as const, label: 'C1–C5', sub: 'High Cervical' },
  { id: 'c6t2' as const, label: 'C6–T2', sub: 'Cervical Intum.' },
  { id: 't3l3' as const, label: 'T3–L3', sub: 'Thoracolumbar' },
  { id: 'l4s3' as const, label: 'L4–S3', sub: 'Lumbosacral Intum.' },
  { id: 'multifocal' as const, label: 'Multifocal', sub: 'Diffuse' },
];

// ─── Differential Diagnosis Maps ─────────────────────────────────────────────

export const DDX_DOG: Record<string, string[]> = {
  t3l3: [
    'IVDD (Hansen Type I/II)',
    'Degenerative myelopathy',
    'Fibrocartilaginous embolic myelopathy (FCEM)',
    'Neoplasia (lymphoma, meningioma, nerve sheath tumor, vertebral)',
    'Discospondylitis',
    'Meningomyelitis (viral, protozoal, autoimmune)',
    'Trauma (vertebral fracture/luxation)',
    'Vertebral malformation (hemivertebra, arachnoid diverticula)',
  ],
  c6t2: [
    'IVDD (Hansen Type I/II)',
    'Cervical spondylomyelopathy (CSM/Wobbler)',
    'Neoplasia (nerve sheath tumor, lymphoma, meningioma)',
    'Fibrocartilaginous embolic myelopathy (FCEM)',
    'Discospondylitis',
    'Trauma (brachial plexus avulsion)',
    'Neuritis (brachial plexus neuritis)',
  ],
  c1c5: [
    'IVDD (Hansen Type I/II)',
    'Cervical spondylomyelopathy (CSM/Wobbler)',
    'Atlantoaxial subluxation',
    'Meningomyelitis (SRMA, GME, infectious)',
    'Neoplasia (meningioma, nerve sheath tumor)',
    'Fibrocartilaginous embolic myelopathy (FCEM)',
    'Discospondylitis',
    'Chiari-like malformation/syringomyelia',
  ],
  l4s3: [
    'Degenerative lumbosacral stenosis (cauda equina)',
    'IVDD (Hansen Type II, L7-S1)',
    'Neoplasia (lymphoma, nerve sheath tumor)',
    'Discospondylitis (L7-S1 predilection)',
    'Fibrocartilaginous embolic myelopathy (FCEM)',
    'Polyradiculoneuritis',
    'Trauma (sacrocaudal fracture/luxation)',
  ],
  prosencephalon: [
    'Neoplasia (meningioma, glioma, lymphoma, metastatic)',
    'MUO (GME, NME, NLE)',
    'Cerebrovascular accident (infarct, hemorrhage)',
    'Metabolic encephalopathy (hepatic, hypoglycemic, uremic, electrolyte)',
    'Idiopathic epilepsy',
    'Anomalous (hydrocephalus, arachnoid cysts)',
    'Infectious (distemper, fungal, protozoal)',
  ],
  brainstem: [
    'Neoplasia (glioma, meningioma, choroid plexus tumor)',
    'MUO (GME)',
    'Infectious (distemper, protozoal, fungal, rickettsial)',
    'Cerebrovascular accident (infarct)',
    'Toxic/metabolic (metronidazole toxicity, thiamine deficiency)',
    'Anomalous (Chiari-like malformation)',
  ],
  cerebellum: [
    'Cerebellar cortical abiotrophy',
    'Anomalous (cerebellar hypoplasia, Dandy-Walker-like)',
    'Inflammatory (MUO, infectious — distemper, Neospora)',
    'Neoplasia (medulloblastoma, meningioma, choroid plexus tumor)',
    'Vascular (cerebellar infarct)',
    'Toxic (metronidazole toxicity)',
  ],
  periph_vest: [
    'Otitis media/interna',
    'Idiopathic vestibular disease',
    'Hypothyroidism (myxedematous/vascular CN VII/VIII)',
    'Ototoxicity (aminoglycosides, chlorhexidine)',
    'Neoplasia (ceruminous gland adenocarcinoma, SCC, polyps)',
    'Congenital vestibular disease',
  ],
  multifocal: [
    'MUO (GME, NME)',
    'Infectious (CDV, FIP, fungal, protozoal, rickettsial)',
    'Neoplasia (lymphoma, metastatic)',
    'Degenerative/metabolic (lysosomal storage disease, metabolic encephalopathy)',
  ],
};

export const DDX_CAT: Record<string, string[]> = {
  t3l3: [
    'Fibrocartilaginous embolic myelopathy (FCEM)',
    'FIP (pyogranulomatous meningomyelitis)',
    'Neoplasia (lymphoma, meningioma, nerve sheath tumor, vertebral)',
    'IVDD (Hansen Type I/II)',
    'Ischemic myelopathy',
    'Discospondylitis',
    'Meningomyelitis (viral, protozoal, autoimmune)',
    'Trauma (vertebral fracture/luxation)',
    'Vertebral malformation (hemivertebra, arachnoid diverticula)',
  ],
  c6t2: [
    'Cervical spondylomyelopathy (CSM/Wobbler)',
    'FIP (pyogranulomatous meningomyelitis)',
    'Neoplasia (nerve sheath tumor, lymphoma, meningioma)',
    'Fibrocartilaginous embolic myelopathy (FCEM)',
    'Discospondylitis',
    'Trauma (brachial plexus avulsion)',
    'Neuritis (brachial plexus neuritis)',
    'IVDD (Hansen Type I/II)',
  ],
  c1c5: [
    'FIP (meningomyelitis)',
    'Cervical spondylomyelopathy (CSM/Wobbler)',
    'Atlantoaxial subluxation',
    'Meningomyelitis (SRMA, GME, infectious)',
    'Neoplasia (meningioma, nerve sheath tumor)',
    'Fibrocartilaginous embolic myelopathy (FCEM)',
    'Ischemic myelopathy',
    'Discospondylitis',
    'IVDD (Hansen Type I/II)',
    'Chiari-like malformation/syringomyelia',
  ],
  l4s3: [
    'Degenerative lumbosacral stenosis (cauda equina)',
    'FIP (pyogranulomatous meningomyelitis)',
    'Neoplasia (lymphoma (more common in cats), nerve sheath tumor)',
    'Discospondylitis (L7-S1 predilection)',
    'Fibrocartilaginous embolic myelopathy (FCEM)',
    'Polyradiculoneuritis',
    'Trauma (sacrocaudal fracture/luxation)',
    'IVDD (Hansen Type II, L7-S1)',
  ],
  prosencephalon: [
    'Neoplasia (meningioma most common, 56-58% of feline brain tumors)',
    'MUO (GME, NME, NLE)',
    'Cerebrovascular accident (infarct, hemorrhage)',
    'Metabolic encephalopathy (hepatic, hypoglycemic, uremic, electrolyte)',
    'FIP (granulomatous meningoencephalitis)',
    'Structural epilepsy (idiopathic uncommon in cats)',
    'Anomalous (hydrocephalus, arachnoid cysts)',
    'Infectious (fungal, protozoal)',
  ],
  brainstem: [
    'Neoplasia (glioma, meningioma, choroid plexus tumor)',
    'MUO (GME)',
    'Infectious (FIP, protozoal, fungal, rickettsial)',
    'Lymphoma',
    'Cerebrovascular accident (infarct)',
    'Toxic/metabolic (metronidazole toxicity, thiamine deficiency)',
    'Anomalous (Chiari-like malformation)',
  ],
  cerebellum: [
    'Cerebellar cortical abiotrophy',
    'Anomalous (cerebellar hypoplasia, Dandy-Walker-like, feline panleukopenia (in utero cerebellar hypoplasia))',
    'Inflammatory (MUO, infectious — FIP, Neospora)',
    'Neoplasia (medulloblastoma, meningioma, choroid plexus tumor)',
    'Vascular (cerebellar infarct)',
    'Toxic (metronidazole toxicity)',
  ],
  periph_vest: [
    'Otitis media/interna',
    'Nasopharyngeal polyp (cats)',
    'Idiopathic vestibular disease',
    'Ototoxicity (aminoglycosides, chlorhexidine)',
    'Neoplasia (ceruminous gland adenocarcinoma, SCC, polyps)',
    'Congenital vestibular disease',
  ],
  multifocal: [
    'FIP (pyogranulomatous meningoencephalomyelitis)',
    'MUO (GME, NME)',
    'Infectious (fungal, protozoal, rickettsial)',
    'Neoplasia (lymphoma, metastatic)',
    'Degenerative/metabolic (lysosomal storage disease, metabolic encephalopathy)',
  ],
};

export function getDdx(loc: string, species: 'Dog' | 'Cat'): string[] {
  return (species === 'Cat' ? DDX_CAT : DDX_DOG)[loc] || [];
}

// ─── Default Data (Normal State) ─────────────────────────────────────────────

export function getDefaultData(): NeuroExamData {
  return {
    // ── T3-L3 ──
    t3l3_gait: 'Normal',
    t3l3_ataxia: 'None',
    t3l3_dpp: 'Present',
    t3l3_reflexes_gate: 'Normal',
    t3l3_patellar: 'Normal',
    t3l3_patellar_side: 'Bilateral',
    t3l3_withdrawal_pl: 'Normal',
    t3l3_withdrawal_pl_side: 'Bilateral',
    t3l3_perineal: 'Normal',
    t3l3_cutoff: 'Normal',
    t3l3_cutoffLevel: 'T13',
    t3l3_pain: false,
    t3l3_kyphosis: false,
    t3l3_schiff: false,
    t3l3_bladder: 'Normal',
    t3l3_tone_pl: 'Normal/Increased',
    t3l3_mass: 'Normal',
    t3l3_postural_tl: 'Normal',
    t3l3_postural_pl: 'Normal',
    t3l3_postural_pl_side: 'Bilateral',

    // ── C6-T2 ──
    c6t2_gait: 'Two-Engine Gait',
    c6t2_amb: 'Ambulatory',
    c6t2_reflexes_gate: 'Normal',
    c6t2_foreReflex: 'Normal',
    c6t2_fore_side: 'Bilateral',
    c6t2_hindReflex: 'Normal/Increased',
    c6t2_hind_side: 'Bilateral',
    c6t2_biceps: 'Normal',
    c6t2_biceps_side: 'Bilateral',
    c6t2_triceps: 'Normal',
    c6t2_triceps_side: 'Bilateral',
    c6t2_horner: 'No',
    c6t2_palpation: 'None',
    c6t2_atrophy: false,
    c6t2_atrophy_side: 'Bilateral',
    c6t2_postural_tl: 'Normal',
    c6t2_postural_tl_side: 'Bilateral',
    c6t2_postural_pl: 'Normal',
    c6t2_postural_pl_side: 'Bilateral',
    c6t2_bladder: 'Normal',

    // ── C1-C5 ──
    c1c5_gait: 'Normal',
    c1c5_ataxia: 'Proprioceptive',
    c1c5_reflexes: 'Normal/Increased',
    c1c5_palpation: 'None',
    c1c5_respiratory: 'Normal',
    c1c5_postural_tl: 'Normal',
    c1c5_postural_tl_side: 'Bilateral',
    c1c5_postural_pl: 'Normal',
    c1c5_postural_pl_side: 'Bilateral',

    // ── L4-S3 ──
    l4s3_gait: 'Normal',
    l4s3_dpp: 'Present',
    l4s3_reflexes_gate: 'Normal',
    l4s3_patellar: 'Normal',
    l4s3_patellar_side: 'Bilateral',
    l4s3_withdrawal: 'Normal',
    l4s3_withdrawal_side: 'Bilateral',
    l4s3_perineal: 'Normal',
    l4s3_tone: 'Normal',
    l4s3_tail_tone: 'Normal',
    l4s3_bladder: 'Normal',
    l4s3_pain: 'None',
    l4s3_atrophy: false,
    l4s3_atrophy_side: 'Bilateral',
    l4s3_mass: 'Normal',
    l4s3_postural_pl: 'Normal',
    l4s3_postural_pl_side: 'Bilateral',

    // ── Prosencephalon ──
    pros_mentation: 'QAR',
    pros_sedation_agent: '',
    pros_amb: 'Ambulatory',
    pros_cp: 'Normal',
    pros_cp_side: 'Left',
    pros_behavior: { pacing: false, pressing: false, hemi: false },
    pros_circle: 'None',
    pros_menace: 'Normal',
    pros_menace_side: 'Left',
    pros_facial: 'Normal',
    pros_facial_side: 'Left',
    pros_focal_sz: 'None',
    pros_focal_sz_side: 'Left',
    pros_plr: 'Normal',
    pros_plr_side: 'Left',

    // ── Brainstem ──
    bs_mentation: 'QAR',
    bs_gait: 'Normal',
    bs_paresis: 'Ambulatory Tetraparesis',
    bs_paresis_side: 'Left',
    bs_ataxia: 'Vestibular',
    bs_cn_eyes: 'Normal',
    bs_cn_eyes_side: 'Left',
    bs_cn_menace: 'Normal',
    bs_cn_plr: 'Normal',
    bs_cn_strabismus: 'Normal',
    bs_cn_vest: 'Normal',
    bs_cn_vest_side: 'Left',
    bs_cn_physiologic_nyst: 'Normal',
    bs_cn_pathologic_nyst: 'None',
    bs_cn_pathologic_nyst_type: 'Horizontal',
    bs_cn_head_tilt: 'None',
    bs_cn_face: 'Normal',
    bs_cn_face_side: 'Left',
    bs_cn_jaw: 'Normal',
    bs_cn_facial_sensation: 'Normal',
    bs_cn_facial: 'Normal',
    bs_cn_gag: 'Normal',
    bs_cn_tongue: 'Normal',
    bs_postural_gate: 'Normal',
    bs_postural_tl: 'Normal',
    bs_postural_tl_side: 'Bilateral',
    bs_postural_pl: 'Normal',
    bs_postural_pl_side: 'Bilateral',

    // ── Peripheral Vestibular ──
    pv_gate: 'Abnormal',
    pv_tilt: 'Left',
    pv_nystagmusType: 'Horizontal',
    pv_nystagmusDir: 'Left',
    pv_positional_nyst: false,
    pv_strabismus: 'None',
    pv_miosis: false,
    pv_enophthalmos: false,
    pv_third_eyelid: false,
    pv_facial: 'Normal',
    pv_proprioception: 'Normal',

    // ── Cerebellum ──
    cb_gate: 'Abnormal',
    cb_mentation: 'QAR',
    cb_gait: 'Hypermetric Ataxia',
    cb_side: 'Bilateral',
    cb_tremor: 'None',
    cb_menace: 'Normal',
    cb_menace_side: 'Bilateral',
    cb_anisocoria: false,
    cb_postural: 'Normal',
    cb_vestibular: false,

    // ── Multifocal ──
    mf_areas: { prosencephalon: false, brainstem: false, cerebellum: false, vestibular: false, c1c5: false, c6t2: false, t3l3: false, l4s3: false },
    mf_mentation: 'QAR',
    mf_sedation_agent: '',
    mf_gait: 'Normal',
    mf_cn: 'Normal',
    mf_cn_detail: '',
    mf_cn_side: 'Bilateral',
    mf_cn_eyes: 'Normal',
    mf_cn_eyes_side: 'Left',
    mf_cn_menace: 'Normal',
    mf_cn_plr: 'Normal',
    mf_cn_strabismus: 'Normal',
    mf_cn_vest: 'Normal',
    mf_cn_vest_side: 'Left',
    mf_cn_physiologic_nyst: 'Normal',
    mf_cn_pathologic_nyst: 'None',
    mf_cn_pathologic_nyst_type: 'Horizontal',
    mf_cn_head_tilt: 'None',
    mf_cn_face: 'Normal',
    mf_cn_face_side: 'Left',
    mf_cn_jaw: 'Normal',
    mf_cn_facial_sensation: 'Normal',
    mf_cn_facial: 'Normal',
    mf_cn_gag: 'Normal',
    mf_cn_tongue: 'Normal',
    mf_reflexes: 'Normal',
    mf_pain: 'None',
    mf_bladder: 'Normal',
    mf_mass: 'Normal',
  };
}

// ─── Initial Exam State ──────────────────────────────────────────────────────

export function INITIAL_LOC_STATE(): LocExamState {
  return {
    version: 2,
    activeLoc: 't3l3',
    species: 'Dog',
    data: getDefaultData(),
    reportLocked: false,
    report: '',
    ddxSelections: {},
  };
}
