import { type LocTemplate } from './types';

export const LOC_TEMPLATES: LocTemplate[] = [
  {
    id: 't3-l3-ivdd',
    name: 'T3-L3 IVDD',
    description: 'Non-amb paraparesis, UMN pelvic, TL pain',
    icon: '🦴',
    localization: 't3l3',
    data: {
      t3l3_gait: 'Non-Ambulatory',
      t3l3_ataxia: 'Proprioceptive',
      t3l3_dpp: 'Present',
      t3l3_reflexes_gate: 'Normal',
      t3l3_pain: true,
      t3l3_kyphosis: true,
      t3l3_bladder: 'Large/Firm (UMN)',
      t3l3_tone_pl: 'Normal/Increased',
      t3l3_postural_pl: 'Absent',
      t3l3_postural_pl_side: 'Bilateral',
      t3l3_postural_tl: 'Normal',
    },
  },
  {
    id: 'c1-c5-myelopathy',
    name: 'C1-C5 Myelopathy',
    description: 'Amb tetraparesis, UMN all limbs, cervical pain',
    icon: '🦴',
    localization: 'c1c5',
    data: {
      c1c5_gait: 'Ambulatory Tetraparesis',
      c1c5_ataxia: 'Proprioceptive',
      c1c5_reflexes: 'Normal/Increased',
      c1c5_palpation: 'Cervical Pain',
      c1c5_postural_tl: 'Deficits',
      c1c5_postural_tl_side: 'Bilateral',
      c1c5_postural_pl: 'Deficits',
      c1c5_postural_pl_side: 'Bilateral',
    },
  },
  {
    id: 'vestibular-peripheral',
    name: 'Peripheral Vestibular',
    description: 'Head tilt, horizontal nystagmus, normal proprioception',
    icon: '👂',
    localization: 'periph_vest',
    data: {
      pv_tilt: 'Left',
      pv_nystagmusType: 'Horizontal',
      pv_nystagmusDir: 'Right',
      pv_positional_nyst: false,
      pv_strabismus: 'None',
      pv_facial: 'Normal',
      pv_proprioception: 'Normal',
    },
  },
  {
    id: 'brain-seizures',
    name: 'Forebrain / Seizures',
    description: 'Obtunded, decreased menace, focal seizures',
    icon: '🧠',
    localization: 'prosencephalon',
    data: {
      pros_mentation: 'Obtunded',
      pros_amb: 'Ambulatory',
      pros_menace: 'Absent',
      pros_menace_side: 'Left',
      pros_cp: 'Decreased',
      pros_cp_side: 'Left',
      pros_circle: 'None',
    },
  },
  {
    id: 'l4-s3-cauda-equina',
    name: 'L4-S3 / Cauda Equina',
    description: 'LMN pelvic, reduced reflexes, LS pain',
    icon: '🦴',
    localization: 'l4s3',
    data: {
      l4s3_gait: 'Paraparesis',
      l4s3_reflexes_gate: 'Abnormal',
      l4s3_patellar: 'Reduced',
      l4s3_patellar_side: 'Bilateral',
      l4s3_withdrawal: 'Reduced',
      l4s3_withdrawal_side: 'Bilateral',
      l4s3_tone: 'Reduced',
      l4s3_pain: 'LS Pain',
      l4s3_postural_pl: 'Deficits',
      l4s3_postural_pl_side: 'Bilateral',
    },
  },
  {
    id: 'normal-exam',
    name: 'Normal Exam',
    description: 'All findings within normal limits',
    icon: '✅',
    localization: 't3l3',
    data: {}, // Empty = all defaults = all normal
  },
];
